### ISSUE TITLE
Jacobian and Hessian

### ISSUE THREAD

**Issue by aunagar** [cmm-20/a1#11]
Hi,
Just to make sure if I understand this sentence correctly - "Implement the method Linkage::dfk_dangles , which computes the Jacobian . To test your implementation with finite differences, run the app test-app . The first test should pass!" -- We compute Jacobian using Finite Difference right? Or are you asking to write it explicitly?

Same question for Hessian. Do we use Finite Difference for that as well, or explicit derivation?
Please clarify!

Best,
Ajay.

**Comment by moritzge** [comment]
Hi Ajay,
Compute both the Jacobian and Hessian analytically. “With Finite Differences” refers to the test-app, which tests your implementation against finite differences. 
Best,
Moritz
