### ISSUE TITLE
Commenting and variables

### ISSUE THREAD

**Issue by Castles-Caves** [cmm-20/a1#2]
Not really an issue to be resolved, but a request!
For the next assignments, would it be possible to add more comments for the variables we are going to be using? Such as, that the angles will be given in radians, x can be n-dimensional, etc. It would help for understanding the code more quickly, as this is not intuitive.

Thanks!

**Comment by moritzge** [comment]
Thanks for the feedback!

If you have any questions about variables or the code in general, feel free to post them here.
Or ask them in the Q&A session on Thursday.
