### ISSUE TITLE
Line Search Method

### ISSUE THREAD

**Issue by chaofiber** [cmm-20/a1#3]
Hello TAs,

Question about the specific method we should use in line search method. Shall we use the exact search method or inexact method such as using Armiju Wolfe Criteria etc.

Thanks

**Comment by printablealice** [comment]
Hello Class,

I am a big fan of the good ol’ bisection method :)

Best,
Jim

**Comment by solraun** [comment]
note that in the constructor of GradientDescenLineSearch, the maxIterations is set to 100 per default. This results in finding the minimum "instantly" because insted of doing only one iteration, we can do many.
It confused me because then my line search seemed much better than it should have been.
