### ISSUE TITLE
RandomMinimizer

### ISSUE THREAD

**Issue by aunagar** [cmm-20/a1#5]
In RandomMinimizer it's written on github that you should use iteration=1 to compare with other optimization techniques. But I don't understand why 1? Am I missing something?

And will RandomMinimizer always output False? Because output has been fixed to False in the starter code and it is outside of the scope of what we can edit.

**Comment by souryavarenya** [comment]
Here's my guess:
1. It should work even with 1 iteration in for loop if the global fBest and xBest is maintained.
2. The output of minimize() being false doesn't matter as long as xBest and fBest are updated

**Comment by souryavarenya** [comment]
@moritzge @printablealice Although I am able to get fBest and xBest in terminal, I am unable to visualize it in the opt-app. Is there anything I'm missing?

**Comment by moritzge** [comment]
First of all, you are not required to return a value at the end of a function. You can return anywhere in a function, even inside a for loop.

The `minimize` methods of all minimizers get called once per frame. In order to see and compare the convergence better, we only want to perform one iteration per frame.

@souryavarenya Can you elaborate a bit more what the issue is?

**Comment by souryavarenya** [comment]
@moritzge The issue I'm facing is that I'm unable to see any trail for random minimizer in the visualization like I can see for other ones.

I'm also not quite sure what to return in the minimize function as it's a bool and is being used like a void method. 

I have been able to print out xBest and fBest on terminal and they seem to be working just fine. It just doesn't reflect in the visualization.

**Comment by souryavarenya** [comment]
@moritzge This can be marked resolved. 
I misunderstood the function description and didn't update to x within the function. I understood the usage of `minimize()` and figured it out.

**Comment by moritzge** [comment]
Ok great! 

For others: in the minimize function, if a new `x` has been found that is better than the previous `x`, store it in `x`.
