### ISSUE TITLE
Issue with drawing of objective function

### ISSUE THREAD

**Issue by antonxy** [cmm-20/a1#6]
Hi,
I am having issues with the drawing of the objective function as visible in the screenshot.

![screenshot_4](https://user-images.githubusercontent.com/4194320/76114284-063d0300-5fe6-11ea-817b-a55704f5b4f1.png)

It seems only the part of the function that was not visible before is redrawn. I can solve that by pressing Recompute Contours. But there still seems to be an offset between where the function is draw and where optimizer path is drawn. The offset changes when moving the function with the right mouse button.

![screenshot_5](https://user-images.githubusercontent.com/4194320/76114932-78621780-5fe7-11ea-94a6-42ef788e53b8.png)

 Any idea how to fix this?

**Comment by antonxy** [comment]
I found a solution/workaround. The problems seem to be due to the pixel ratio, it is set to 1.25 by default on my laptop. If I set that to 1.0 it works. Moving the function landscape is still a bit glitchy, but with pressing Recompute Contours from time to time it is usable.

**Comment by moritzge** [comment]
As @antonxy mentioned, change the pixelRatio to 1 and click recompute contours if you see these glitches.
