### ISSUE TITLE
Convergence of Newton Method

### ISSUE THREAD

**Issue by chaofiber** [cmm-20/a1#7]
Hello all,

When I tried Newton method (without damping), I found that if the initial point is far away from the equilibrium point, the newton method is not guaranteed to converge to minimum (which is the case), but as far as I understood, the newton method should converge to a gradient zero point, I print out the gradient in the process, but it is not zero even if it is almost converges. I want to ask if it is normal based on the given code?

A possible reason I think is that I am not sure what stepsize to choose after MaxLineSearch is reached? I just chose stepsize = 1 if cannot find a proper stepsize within MaxLineSearch, is there any better options?

Best,

**Comment by chaofiber** [comment]
Seems that Newton method stop immediately after one step....so confusing.. Following is the code hope someone can help..

function->getHessian(x, hessian);
function->addGradientTo(x, grad);
Eigen::SimplicialCholesky<SparseMatrixd> chol(hessian);
dx = chol.solve(grad);


where hessian and grad are both properly declared.

**Comment by moritzge** [comment]
About the step size: if MaxLineSearch is reached, you could, for example, take a step alpha*dx, (where alpha=beta^MaxLineSearch, since we have reduced alpha MaxLineSearch-times with a factor of beta).

Do you still have the problem where Newton stops after 1 iteration? If so, maybe you can provide a bit more details.

**Comment by chaofiber** [comment]
> About the step size: if MaxLineSearch is reached, you could, for example, take a step alpha*dx, (where alpha=beta^MaxLineSearch, since we have reduced alpha MaxLineSearch-times with a factor of beta).
> 
> Do you still have the problem where Newton stops after 1 iteration? If so, maybe you can provide a bit more details.
 
I fixed that problem after applied this stepsize. Thanks
