### ISSUE TITLE
SearchDomain in ik-app

### ISSUE THREAD

**Issue by chaofiber** [cmm-20/a1#8]
Hello TAs,

In the ik-app, when using the Random Minimizer, I found that the search domain is very confusing. I printed out the searchDomanMax and searchDomainMin as follows:
searchDomainMax: [6.9002e-310, 6.9002e-310]
searchDomainMin: [-0.00141162, 6.9002e-310]

which implies the target end-effector can never be achieved by Random Minimizer. I think there is something wrong with the ik-app code when initializing the searchDomain. Please take a look.

Best,

**Comment by moritzge** [comment]
Hi chaofiber,

Either don't use the random minimizer in the ik-app, or set the search domain yourself. 

Best,
Moritz
